import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.inmotionhosting.com/shared-hosting');
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.getByText('InMotion Hosting Home VPS').click();
  await page.getByRole('button', { name: 'All Hosting' }).click();
  await page.getByLabel('Shared Hosting', { exact: true }).click();
  await page.getByText('Hassle-Free Website Migration', { exact: true }).click();
  await page.getByText('Free Domain, SSL, and Email').click();
  await page.getByRole('link', { name: 'See Plans and Pricing' }).click();
  await page.getByRole('button', { name: 'Starter' }).click();
  await page.getByRole('button', { name: 'Premium' }).click();
  await page.getByRole('link', { name: 'Select' }).first().click();
  await page.locator('#mat-radio-3 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click();
  await page.locator('central-header').getByRole('link', { name: 'InMotion Hosting Logo' }).click();
  await page.getByRole('button', { name: 'All Hosting' }).click();
  await page.getByRole('button', { name: 'All Hosting' }).click();
  await page.getByRole('link', { name: 'View Deals' }).click();
  await page.getByRole('menuitem', { name: 'All Hosting' }).click();
  await page.getByLabel('Shared Hosting', { exact: true }).click();
  await page.getByRole('link', { name: 'See Plans and Pricing' }).click();
  await page.getByRole('list').filter({ hasText: 'Hosting Plus: Python, Node.JS' }).click();
  await page.locator('.col-lg-7.col-md-7.col-sm-12.col-xs-12.align-column-center').click();
  await page.getByText('Get the speed, security, and').click();
  await page.getByRole('button', { name: 'Developer Tools Get the Best' }).click();
  await page.getByRole('button', { name: 'Web Security Secure Shared' }).click();
  await page.getByRole('button', { name: 'eCommerce Tools The Best' }).click();
  await page.getByRole('button', { name: 'NVMe SSD Storage NVMe SSDs' }).click();
  await page.getByRole('link', { name: 'Choose Your Plan' }).first().click();
  await page.getByRole('link', { name: 'Select' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'smsChat NowcallCall' }).nth(2).click();
  await page.locator('central-header').getByRole('link', { name: 'InMotion Hosting Logo' }).click();
  await page.getByRole('menuitem', { name: 'All Hosting' }).click();
  await page.getByLabel('Shared Hosting', { exact: true }).click();
  await page.getByRole('link', { name: 'Choose Your Plan' }).nth(1).click();
  await page.locator('a').filter({ hasText: 'What is Shared Hosting Best' }).click();
  await page.locator('a').filter({ hasText: 'How many websites can I host' }).click();
  await page.locator('a').filter({ hasText: 'Is shared hosting a good' }).click();
  await page.locator('a').filter({ hasText: 'Why does InMotion Hosting use' }).click();
  await page.locator('a').filter({ hasText: 'What data center locations do' }).click();
  await page.locator('a').filter({ hasText: 'What are the downsides of' }).click();
  await page.locator('a').filter({ hasText: 'Is shared web hosting' }).click();
  await page.locator('.col-lg-8.col-md-7').click();
  await page.locator('a').filter({ hasText: 'What happens if I outgrow' }).click();
});