import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByText('Web Hosting Solutions March').click();
  await page.getByText('Dedicated Hosting: AMD EPYC').click();
  await page.locator('#post-2').getByRole('link', { name: 'Bare Metal Servers' }).click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByRole('link', { name: 'High-Capacity Servers' }).click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByRole('link', { name: 'View Plans & Pricing' }).click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByRole('link', { name: 'View Deals' }).click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByRole('link', { name: 'Explore VPS Options' }).click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByRole('link', { name: 'Explore Server Options' }).first().click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.locator('div').filter({ hasText: 'VPS Hosting Fast, reliable' }).nth(5).click();
  await page.locator('.col-md-12').first().click();
  await page.getByText('Launch Fast With Confidence Get started quickly with streamlined setup, a free').click();
  await page.getByText('24/7 Human Support Every').click();
  await page.locator('#sp-wp-carousel-pro-id-19489').click();
  await page.getByRole('link', { name: 'Web Hosting Plans' }).click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByText('Empower What’s Next Enterprise-Grade Solutions for Every Stage of Growth Large').click();
  await page.getByRole('link', { name: 'Learn More' }).first().click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByRole('link', { name: 'See Managed Hosting Services' }).click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByRole('link', { name: 'Learn More' }).nth(2).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('textbox', { name: 'First Name*' }).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('textbox', { name: 'Last Name*' }).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('textbox', { name: 'Business Email*' }).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('textbox', { name: 'Phone Number' }).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('textbox', { name: 'Phone Number' }).click();
  await page.locator('.col-lg-2').first().click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.locator('#imh-search-form div').filter({ hasText: 'Choose Your Domain: Go' }).click();
  await page.getByRole('button', { name: 'Go' }).click();
  await page.getByRole('link', { name: 'Compare Plans' }).first().click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.locator('.col-lg-7').click();
  await page.locator('a').filter({ hasText: 'What are the different types' }).click();
  await page.locator('a').filter({ hasText: 'Do I really need a host for' }).click();
  await page.locator('a').filter({ hasText: 'How do I switch website' }).click();
  await page.locator('a').filter({ hasText: 'Why should I choose InMotion' }).click();
  await page.locator('a').filter({ hasText: 'Who owns InMotion Hosting?' }).click();
  await page.locator('a').filter({ hasText: 'Where is InMotion Hosting' }).click();
  await page.locator('a').filter({ hasText: 'How many websites can you' }).click();
  await page.locator('a').filter({ hasText: 'Does InMotion Hosting provide' }).click();
  await page.getByRole('link', { name: 'Amsterdam, Netherlands' }).click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByText('A Business Owner’s Guide to Virtual Private ServersApril 3, 2026Best CMS').click();
  await page.getByText('A Business Owner’s Guide to Virtual Private ServersApril 3,').click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByText('Best CMS Platforms for 2026: A Practical ComparisonApril 1,').click();
  await page.locator('[data-test-id="interactive-frame"]').contentFrame().getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByRole('button', { name: 'Cookies Settings' }).click();
  await page.locator('.ot-switch-nob').first().click();
  await page.locator('.ot-switch-nob').first().click();
  await page.getByRole('button', { name: 'Close' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('.imh-social').click();
  const page1 = await page1Promise;
  await page.getByText('Shared Hosting Hosting for').click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByText('WordPress WooCommerce Hosting').click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  const page2Promise = page.waitForEvent('popup');
  await page.getByText('Live Chat + 757-350-8523 +44 2045 763722 Support Center Resources Community').click();
  const page2 = await page2Promise;
  await page.getByText('Contact Us About Us Blog News').click();
  await page.getByText('Terms of Service | Privacy').click();
  await page.locator('div').filter({ hasText: 'Copyright © 2002-2026' }).nth(4).click();
});