import { test, expect } from '@playwright/test';

test('test inmotion-hosting.spec.js @sanity', async ({ page }) => {
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByRole('link', { name: 'Dedicated Hosting' }).click();
  await page.locator('#post-2').getByRole('link', { name: 'Bare Metal Servers' }).click();
  await page.getByRole('link', { name: 'Eco Servers' }).click();
  await page.getByRole('link', { name: 'High-Capacity Servers' }).click();
  await page.getByRole('link', { name: 'View Plans & Pricing' }).click();
  await page.getByRole('link', { name: 'View Deals' }).click();
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByRole('link', { name: 'Explore VPS Options' }).click();
  await page.getByRole('link', { name: 'Explore Server Options' }).first().click();
  await page.getByRole('link', { name: 'Explore Server Options' }).nth(1).click();
  await page.getByRole('link', { name: 'Explore Server Options' }).nth(2).click();
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByText('Launch AssistTriangle Icon').click();
  await page.locator('.col-md-12').first().click();
  await page.getByRole('heading', { name: 'Launch Fast With Confidence' }).click();
  await page.getByRole('paragraph').nth(2).click();
  await page.getByText('24/7 Human Support Every').click();
  await page.getByRole('img', { name: 'Monarx logo' }).first().click();
  await page.getByRole('img', { name: 'nginx logo' }).first().click();
  await page.getByRole('img', { name: 'OpenStack logo' }).first().click();
  await page.getByRole('img', { name: 'SaltStack logo' }).first().click();
  await page.getByRole('img', { name: 'Virtuozzo logo' }).first().click();
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByRole('link', { name: 'Learn More' }).first().click();
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByRole('link', { name: 'Learn More' }).nth(1).click();
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByRole('link', { name: 'See Managed Hosting Services' }).click();
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByRole('link', { name: 'Learn More' }).nth(2).click();
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByRole('paragraph').filter({ hasText: 'Learn More' }).nth(3).click();
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByText('Europe – Amsterdam Data Center Home to four of the world’s largest internet').click();
  await page.goto('https://www.inmotionhosting.com/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Chat with us 1' }).click();
  const page1 = await page1Promise;
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('qa');
  await page.getByRole('button', { name: 'Go' }).click();
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByRole('link', { name: 'Compare Plans' }).first().click();
  await page.getByRole('heading', { name: 'Scalable Hosting That Grows' }).click();
  await page.getByText('Shared Hosting Scalable').click();
  await page.getByRole('link', { name: 'See Plans and Pricing' }).click();
  await page.getByText('Starting at$3.49/moRenews at').click();
  await page.goto('https://www.inmotionhosting.com/');
  await page.locator('a').filter({ hasText: 'What are the different types' }).click();
  await page.getByText('We also offer web hosting').click();
  await page.getByText('At InMotion Hosting, we take pride in offering a range of web hosting plans,').click();
  await page.locator('a').filter({ hasText: 'Do I really need a host for' }).click();
  await page.getByText('Yes, you do need a host for').click();
  await page.getByText('A web hosting service').click();
  await page.locator('a').filter({ hasText: 'How do I switch website' }).click();
  await page.getByText('At InMotion, we make it easy').click();
  await page.getByText('We offer a free plugin if you').click();
  await page.getByText('Your data, website, and').click();
  await page.locator('a').filter({ hasText: 'How does InMotion\'s money-' }).click();
  await page.getByText('We strive to provide the best').click();
  await page.getByText('If you have prepaid yearly,').click();
  await page.locator('div:nth-child(10) > .col-lg-12 > div > p').first().click();
  await page.locator('a').filter({ hasText: 'Why should I choose InMotion' }).click();
  await page.locator('div:nth-child(12) > .col-lg-12 > div > p').first().click();
  await page.locator('a').filter({ hasText: 'Who owns InMotion Hosting?' }).click();
  await page.locator('a').filter({ hasText: 'Where is InMotion Hosting' }).click();
  await page.getByRole('link', { name: 'Los Angeles, CA', exact: true }).click();
  await page.locator('a').filter({ hasText: 'Does InMotion Hosting provide' }).click();
  await page.locator('a').filter({ hasText: 'How many websites can you' }).click();
  await page.locator('a').filter({ hasText: 'Where is InMotion Hosting' }).click();
  await page.getByRole('link', { name: 'Singapore' }).click();
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByText('A Business Owner’s Guide to Virtual Private ServersApril 3,').click();
  await page.getByText('Best CMS Platforms for 2026: A Practical ComparisonApril 1,').click();
  await page.locator('[data-test-id="interactive-frame"]').contentFrame().getByRole('button', { name: 'Close' }).click();
  await page.locator('iframe[title="Interactive or visual content"]').contentFrame().locator('.fl-chart-interaction').click();
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'facebook' }).click();
  const page2 = await page2Promise;
  const page3Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'github' }).click();
  const page3 = await page3Promise;
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'youtube' }).click();
  const page4 = await page4Promise;
  await page.getByRole('link', { name: 'Shared Hosting' }).click();
  await page.getByText('Shared Hosting Hosting for').click();
  await page.getByText('WordPress WooCommerce Hosting').click();
  const page5Promise = page.waitForEvent('popup');
  await page.getByText('Live Chat + 757-350-8523 +44 2045 763722 Support Center Resources Community').click();
  const page5 = await page5Promise;
  await page.getByText('Contact Us About Us Blog News').click();
  await page.getByRole('menuitem', { name: 'Contact Us', exact: true }).click();
  await page.getByRole('link', { name: 'Contact Us' }).click();
  await page.getByRole('menuitem', { name: 'About Us' }).click();
  await page.getByRole('menuitem', { name: 'About Us' }).click();
  await page.getByRole('menuitem', { name: 'Blog' }).click();
  await page.getByRole('link', { name: 'News' }).click();
  await page.getByRole('link', { name: 'Careers' }).click();
  await page.locator('.imh-ds-icon.close').click();
  const page6Promise = page.waitForEvent('popup');
  await page.locator('.imh-ds-icon.commenting').click();
  const page6 = await page6Promise;
  await page.getByRole('button', { name: 'Accept All Cookies' }).click();
  await page.getByText('Support Live Chat + 757-350-').click();
  await page.locator('div').filter({ hasText: 'Copyright © 2002-2026' }).nth(3).click();
  await page.locator('div').filter({ hasText: 'InMotionHosting.com provides' }).nth(4).click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
});