import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.inmotionhosting.com/');
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.getByRole('link', { name: 'Server Management' }).click();
  await page.getByRole('heading', { name: 'Your Dedicated Team of' }).click();
  await page.locator('.container > .row').first().click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Chat with us 1' }).click();
  const page1 = await page1Promise;
  await page.locator('#benefits > .container > div > div:nth-child(2)').click();
  await page.getByRole('button', { name: '6 Month' }).click();
  await page.getByRole('button', { name: '3 Month' }).click();
  await page.getByRole('button', { name: 'Year' }).click();
  await page.getByText('Solutions Pro Level 1 Quick,').click();
  await page.getByText('Solutions Pro Level 2 More').click();
  await page.getByText('You Save 15% 1 Hour Pay-as-').click();
  await page.getByRole('paragraph').filter({ hasText: '$169.15' }).click();
  await page.getByText('You Save 15% Launch Assist').click();
  await page.getByRole('link', { name: 'Chat with us 2' }).click();
  await page1.getByRole('textbox', { name: 'Your Name: *' }).click();
  await page.locator('.boldgrid-section > .container > div:nth-child(2)').first().click();
  await page.getByText('Managed WordPress Purpose').click();
  await page.getByText('PageSpeed Pros Guarantee Fully Managed Medium Site with Heavy Traffic Starting').click();
  await page.getByText('PageSpeed Pros Guarantee Enterprise Large Dynamic Site with Heavy Traffic').click();
  await page.getByText('Effortless WordPress Website Management Simplify your operations with our fully').click();
  await page.getByRole('link', { name: 'Optimized Website Performance' }).click();
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.locator('#swiper-wrapper-4c5b77a9d3cc46105').click();
  await page.locator('a').filter({ hasText: 'Why should I subscribe to' }).click();
  await page.locator('a').filter({ hasText: 'What will InMotion Solutions' }).click();
  await page.locator('a').filter({ hasText: 'What can InMotion Solutions' }).click();
  await page.locator('a').filter({ hasText: 'How do I purchase InMotion' }).click();
  await page.locator('.boldgrid-section.custom-block > .container > div > .col-lg-7').click();
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.getByRole('link', { name: 'Custom Website Design' }).click();
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.getByRole('link', { name: 'QuickSite' }).click();
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.getByRole('link', { name: 'Website Rebuild' }).click();
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.getByRole('link', { name: 'All Website Services' }).click();
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.getByRole('link', { name: 'Maintenance Plans for' }).click();
  await page.getByRole('button', { name: 'Year' }).click();
  await page.getByRole('button', { name: 'Month' }).click();
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.getByRole('link', { name: 'Hacked Website Repair' }).click();
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.getByRole('link', { name: 'Speed Optimization' }).click();
  await page.getByRole('button', { name: 'Website Services' }).click();
  await page.getByRole('link', { name: 'Maintenance Plans for' }).click();
});