import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.inmotionhosting.com/dedicated-servers');
  await page.getByText('Dedicated Server Hosting Dedicated Server Hosting with Superior Performance Our').click();
  await page.getByRole('link', { name: 'View Plans and Pricing' }).click();
  await page.getByText('Choose The Level of Management That Fits Your Operation Every Dedicated Server').click();
  await page.getByRole('row', { name: 'Server Setup and' }).getByRole('strong').click();
  await page.getByRole('cell', { name: '/7 Human Support' }).click();
  await page.locator('span').filter({ hasText: 'Custom Server' }).click();
  await page.locator('span').filter({ hasText: '+ Premier Care Server' }).click();
  await page.locator('tr:nth-child(6) > td:nth-child(2) > .fa').click();
  await page.locator('.fa.fa-imh-minus').first().click();
  await page.locator('tr:nth-child(7) > .check').click();
  await page.locator('tr:nth-child(6) > td:nth-child(3)').first().click();
  await page.getByRole('cell', { name: 'Monarx Security ($19.99/mo' }).click();
  await page.getByRole('cell', { name: '500GB Backup Storage Space ($' }).click();
  await page.getByRole('cell', { name: 'InMotion Solutions 1hr/mo ($' }).click();
  await page.getByRole('button', { name: 'Custom Servers That Give You' }).click();
  await page.getByRole('button', { name: 'Starter Entry-Level Servers' }).click();
  await page.getByRole('button', { name: 'Premier Care Managed Servers' }).click();
  await page.getByRole('link', { name: 'Select' }).first().click();
  await page.locator('.mat-select-arrow-wrapper').first().click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.locator('.mat-select-arrow-wrapper.ng-tns-c45-36').click();
  await page.getByText('AlmaLinux 9').click();
  await page.locator('.mat-select-arrow-wrapper.ng-tns-c45-50').click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.getByRole('combobox', { name: 'InMotion Dedicated Premier' }).click();
  await page.locator('#mat-option-322').getByText('InMotion Dedicated Premier').click();
  await page.locator('.ng-tns-c45-44 > .ctw-flex').click();
  await page.locator('div').filter({ hasText: /^US East$/ }).click();
  await page.getByRole('combobox', { name: 'US East' }).click();
  await page.locator('div').filter({ hasText: /^US West$/ }).click();
  await page.getByText('My Cart #A28FDDBAE7 USDCurrencyPRODUCTPRICE Essential G4 - Web Hosting 1 Month').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('div').filter({ hasText: /^Email \*$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Create Password \*$/ }).click();
  await page.getByText('OR', { exact: true }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: '(201) 555-' }).click();
  await page.getByRole('textbox', { name: 'Company Name' }).click();
  await page.getByRole('textbox', { name: 'Address Line 1' }).click();
  await page.locator('div').filter({ hasText: /^Address Line 2$/ }).nth(4).click();
  await page.getByRole('textbox', { name: 'City' }).click();
  await page.locator('div').filter({ hasText: /^State \*$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Address Line 2$/ }).nth(4).click();
  await page.locator('div').filter({ hasText: /^Postal Code \*$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Country \*$/ }).nth(1).click();
  await page.getByText('Bangladesh', { exact: true }).click();
  await page.locator('div').filter({ hasText: 'shopping_cartOrder Summary My' }).nth(4).click();
  await page.locator('select').selectOption('1091_15847');
  await page.getByText('Credit Card PayPal Credit').click();
  await page.locator('.alert.alert-default').click();
  await page.locator('.mat-checkbox-inner-container').click();
  await page.locator('.mat-checkbox-inner-container').click();
  await page.locator('iframe[src="https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/f/ov2/av0/rch/d4ge9/0x4AAAAAAA6E25dbi4yymbE5/auto/fbE/new/normal?lang=auto"]').contentFrame().locator('body').click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.locator('central-header').getByRole('link', { name: 'InMotion Hosting Logo' }).click();
  await page.getByRole('link', { name: 'View Plans & Pricing' }).click();
  await page.locator('.row.imh-rounded-shadow > div:nth-child(3)').click();
  await page.getByText('Premier Care gives you guided').click();
  await page.getByRole('img', { name: 'White Glove Service Icon' }).click();
  await page.getByRole('link', { name: 'Learn More' }).first().click();
  await page.getByRole('link', { name: 'Learn More' }).nth(1).click();
  await page.getByRole('button', { name: 'Customizable Powerful' }).click();
  await page.getByRole('button', { name: 'Security Highest-Grade' }).click();
  await page.getByRole('button', { name: 'Tier 1 Network An Ultra-' }).click();
  await page.getByRole('button', { name: 'Scalability Enterprise-Grade' }).click();
  await page.locator('#dedicated-servers-learn-more-button').click();
  await page.getByRole('link', { name: 'InMotion Hosting Logo InMotion Hosting Home' }).click();
  await page.getByRole('link', { name: 'View Plans & Pricing' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Chat with us 7' }).click();
  const page1 = await page1Promise;
  await page.getByRole('link', { name: 'Choose Your Server' }).click();
  await page.getByRole('link', { name: 'Select' }).nth(3).click();
  await page.locator('central-header').getByRole('link', { name: 'InMotion Hosting Logo' }).click();
  await page.getByRole('link', { name: 'View Plans & Pricing' }).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('textbox', { name: 'First Name*' }).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('textbox', { name: 'Last Name' }).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('group').filter({ hasText: 'Phone Number**Afghanistan' }).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('textbox', { name: 'Phone Number*' }).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('textbox', { name: 'Business Email*' }).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('textbox', { name: 'Company Name' }).click();
  await page.locator('iframe[title="Form 0"]').contentFrame().getByRole('button', { name: 'Submit' }).click();
  await page.locator('a').filter({ hasText: 'What is a Dedicated Server?' }).first().click();
  await page.locator('a').filter({ hasText: 'What security / DDoS' }).click();
  await page.locator('a').filter({ hasText: 'How do I migrate my website' }).click();
  await page.locator('a').filter({ hasText: 'How do I migrate my website' }).click();
  await page.locator('a').filter({ hasText: 'How do I migrate my website' }).click();
  await page.locator('a').filter({ hasText: 'Do you offer fully managed' }).click();
  await page.locator('a').filter({ hasText: 'What data center locations do' }).click();
  await page.locator('a').filter({ hasText: 'Which Dedicated Hosting plan' }).click();
  await page.locator('a').filter({ hasText: 'Do I need a Dedicated Hosting' }).click();
  await page.locator('a').filter({ hasText: 'Do I need a Dedicated Hosting' }).click();
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('listitem').filter({ hasText: 'What is a Dedicated Server?' }).click();
  const page2 = await page2Promise;
});